"""add cities table and city_id to venues

Revision ID: 4e2f5c6e0983
Revises: 6010a1a8a2c1
Create Date: 2026-06-23 10:42:40.299923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4e2f5c6e0983'
down_revision: Union[str, None] = '6010a1a8a2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('popular', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venues', sa.Column('city_name', sa.String(length=100), nullable=True))
    op.add_column('venues', sa.Column('city_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'venues', 'cities', ['city_id'], ['id'])
    op.drop_column('venues', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'city_id')
    op.drop_column('venues', 'city_name')
    op.drop_table('cities')
    # ### end Alembic commands ###