"""add precision field to venues (retry)

Revision ID: ba4d85521d79
Revises: 6fbc06552358
Create Date: 2026-07-20 22:31:24.741823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ba4d85521d79'
down_revision: Union[str, None] = '6fbc06552358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('precision', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'precision')
    # ### end Alembic commands ###