"""add city_id to events

Revision ID: d45b7ab859e1
Revises: 4e2f5c6e0983
Create Date: 2026-06-24 14:41:11.122134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd45b7ab859e1'
down_revision: Union[str, None] = '4e2f5c6e0983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('city_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'events', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'city_id')
    # ### end Alembic commands ###